name: Publish package to GitHub Packages
on:
  push:
    branches: [ github_publish ]
#  pull_request:
#    types: [ opened, synchronize, reopened ]
#  release:
#    types: [created]
jobs:
  publish:
    name: publish gh
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          ST_PWD: ${{secrets.ST_PWD}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          ST_UID: ${{secrets.ST_UID}}
          GPG_KEY: ${{secrets.GPG_SECRET_KEY}}
          GPG_KEY_ID: ${{secrets.GPG_KEY_ID}}
          GPG_PWD: ${{secrets.GPG_SECRET_KEY_PASSWORD}}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publish
            -Psonar_token=${{env.SONAR_TOKEN}}
            -Pst_pwd=${{env.ST_PWD}}
            -Pst_uid=${{env.ST_UID}}
            -Pgh_actor=${{env.GITHUB_TOKEN}}
            -Pgh_token=${{env.GITHUB_ACTOR}}
            -PsigningKeyId=${{env.GPG_KEY_ID}}
            -PsigningKey=${{env.GPG_KEY}}
            -PsigningPassword=${{env.GPG_PWD}}